import RPi.GPIO as GPIO

GPIO.setmode(GPIO.BCM)
GPIO.setup(17,GPIO.OUT)
GPIO.setup(17, GPIO.HIGH)
GPIO.setup(27,GPIO.OUT)
GPIO.setup(27, GPIO.HIGH)
GPIO.setup(22,GPIO.OUT)
GPIO.setup(22, GPIO.HIGH)
GPIO.setup(23,GPIO.OUT)
GPIO.setup(23, GPIO.HIGH)
